/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary": "#ffffff",
        "error": "#ffb4ab",
        "on-secondary": "#003918",
        "on-error-container": "#ffdad6",
        "surface-variant": "#333539",
        "on-tertiary-fixed": "#410004",
        "surface-container-low": "#1a1c20",
        "on-primary": "#1e1b4b",
        "on-primary-fixed": "#1e1b4b",
        "outline": "#6b7280",
        "secondary-fixed-dim": "#a78bfa",
        "inverse-primary": "#4c1d95",
        "inverse-on-surface": "#2f3035",
        "on-surface-variant": "#9ca3af",
        "on-background": "#e2e2e8",
        "primary-fixed-dim": "#c4b5fd",
        "on-secondary-container": "#1e1b4b",
        "surface-container-highest": "#333539",
        "surface-container-high": "#282a2e",
        "primary": "#ffffff",
        "on-tertiary": "#1e1b4b",
        "on-error": "#690005",
        "surface-bright": "#37393e",
        "on-secondary-fixed": "#1e1b4b",
        "tertiary-fixed": "#ede9fe",
        "surface-container-lowest": "#0c0e12",
        "surface": "#111317",
        "primary-container": "#a78bfa",
        "background": "#111317",
        "tertiary-container": "#ede9fe",
        "outline-variant": "#3d3d4a",
        "on-primary-fixed-variant": "#4c1d95",
        "on-tertiary-container": "#4c1d95",
        "surface-container": "#1e2024",
        "secondary-container": "#7c3aed",
        "on-surface": "#e2e2e8",
        "secondary": "#c4b5fd",
        "on-primary-container": "#4c1d95",
        "tertiary-fixed-dim": "#c4b5fd",
        "primary-fixed": "#a78bfa",
        "on-tertiary-fixed-variant": "#4c1d95",
        "on-secondary-fixed-variant": "#3b0764",
        "secondary-fixed": "#ddd6fe",
        "surface-dim": "#111317",
        "inverse-surface": "#e2e2e8",
        "surface-tint": "#a78bfa",
        "error-container": "#93000a"
      },
      fontFamily: {
        "headline": ["Space Grotesk", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
    },
  },
  plugins: [],
}
